import = [
  "~/.config/alacritty/themes/aura.toml"
]

[window]

padding = { x = 10, y = 10 }
title = "Terminal"
dynamic_title = true
dynamic_padding = true
opacity = 0.95
#blur = true
dimensions = { columns = 100, lines = 30 }
startup_mode = "Maximized"


[font]
size = 12

[font.normal]
family = "Iosevka Nerd Font"
