---
- name: Install hyprland packages
  become: true
  community.general.pacman:
    name:
      # Core
      - hyprland
      - hyprpaper
      - hyprlock

      # Utils
      - jq
      - swappy
      - wl-clipboard
      - slurp
      - grim
      - nwg-displays

      # Theming
      - qt5ct
      - qt6ct
      - kvantum
      - kvantum-qt5

      # Themes
      - kvantum-theme-materia
      - materia-gtk-theme
  when: ansible_distribution == "Archlinux"

- name: Install hyprland aur packages
  kewlfft.aur.aur:
    name:
      # Cursors
      - rose-pine-cursor
      - rose-pine-hyprcursor
  when: ansible_distribution == "Archlinux"

- name: Deploy hyprland config
  ansible.builtin.file:
    src: "{{ role_path }}/files/hypr"
    dest: ~/.config/hypr
    state: link
    force: true
