---
- name: Install hyprland packages
  become: true
  community.general.pacman:
    name:
      # Core
      - hyprland
      - hyprpaper
      - hyprlock

      # Utils
      - jq # JSON parser
      - swappy # Screenshot editor
      - wl-clipboard # Clipboard manager
      - slurp # Screenshot capture
      - grim # Screenshot capture
      - nwg-displays # Display manager

      # Theming
      - qt5ct
      - qt6ct
      - kvantum
      - kvantum-qt5

      # Gnome packages
      - gnome-themes-extra # Themes
      - nautilus # File manager
      - polkit-gnome # Polkit
      - libadwaita # GTK theme
      - adwaita-icon-theme # Icons
  when: ansible_distribution == "Archlinux"

- name: Install hyprland aur packages
  kewlfft.aur.aur:
    name:
      # Best cursors
      - rose-pine-cursor
      - rose-pine-hyprcursor

      # Apps
      - pwvucontrol # Volume control
      - overskride-bin # Bluetooth
      - loupe # View images
  when: ansible_distribution == "Archlinux"

- name: Deploy hyprland config
  ansible.builtin.file:
    src: "{{ role_path }}/files/hypr"
    dest: ~/.config/hypr
    state: link
    force: true

- name: Install xdg-portals packages
  become: true
  community.general.pacman:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-hyprland
      # Only for gtk theme
      - xdg-desktop-portal-gnome
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
  when: ansible_distribution == "Archlinux"

- name: Deploy xdg-portals config
  ansible.builtin.file:
    src: "{{ role_path }}/files/xdg-desktop-portal"
    dest: ~/.config/xdg-desktop-portal
    state: link
    force: true
  when: ansible_distribution == "Archlinux"
