---
- name: Install hyprland packages
  become: true
  community.general.pacman:
    name:
      - hyprland
      - hyprpaper
      - hyprlock
      - jq
      - swappy
      - wl-clipboard
      - slurp
      - grim
      - nwg-displays
  when: ansible_distribution == "Archlinux"

- name: Install hyprland aur packages
  community.general.pacman:
    name:
      # Cursors
      - rose-pine-cursor
      - rose-pine-hyprcursor

      # Themes
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: Deploy hyprland config
  ansible.builtin.file:
    src: "{{ role_path }}/files/hypr-{{ ansible_facts['nodename'] }}"
    dest: ~/.config/hypr
    state: link
    force: true
