---
- name: Install hyprland packages
  become: true
  community.general.pacman:
    name:
      - hyprland
      - hyprpaper
      - hyprlock
      - jq
      - swappy
      - wl-clipboard
      - slurp
      - grim
      - nwg-displays
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Deploy hyprland config
  ansible.builtin.file:
    src: "{{ role_path }}/files/hypr-{{ ansible_facts['nodename'] }}"
    dest: ~/.config/hypr
    state: link
    force: true
