preload = ~/.dotfiles/wallpapers/berserk.jpg
preload = ~/.dotfiles/wallpapers/sombrero-galaxy.jpg

wallpaper = eDP-1,~/.dotfiles/wallpapers/sombrero-galaxy.jpg
wallpaper = HDMI-A-1,~/.dotfiles/wallpapers/sombrero-galaxy.jpg
wallpaper = DVI-D-1,~/.dotfiles/wallpapers/sombrero-galaxy.jpg

splash = false
ipc = off
