preload = ~/.dotfiles/wallpapers/berserk.jpg

wallpaper = eDP-1,~/.dotfiles/wallpapers/berserk.jpg
wallpaper = HDMI-A-1,~/.dotfiles/wallpapers/berserk.jpg
wallpaper = DVI-D-1,~/.dotfiles/wallpapers/berserk.jpg

splash = false
ipc = off
