source=~/.dotfiles/hypr/base.conf

monitor=eDP-1,preferred,0x0,1.5
monitor=HDMI-A-1,preferred,0x-1080,1

exec-once = ~/.dotfiles/hypr/scripts/portal.sh

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland,x11

xwayland {
  force_zero_scaling = true
}
