preload = ~/.dotfiles/wallpapers/.wallpaper

wallpaper = eDP-1,~/.dotfiles/wallpapers/.wallpaper
wallpaper = HDMI-A-1,~/.dotfiles/wallpapers/.wallpaper
wallpaper = DVI-D-1,~/.dotfiles/wallpapers/.wallpaper

splash = false
ipc = off
