format = """$character"""
right_format = """$all"""
add_newline = false

[battery]
disabled = true

[aws]
disabled = true

[nodejs]
symbol = "[󰋘](green) "

[character]
format = "$symbol  "
success_symbol = "[](green)"
error_symbol = "[](red)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "

[git_status]
deleted = ' $count '
renamed = ' $count '
staged = ' $count '
modified = ' $count '
stashed = ' $count '
ahead = ' ${count} '
diverged = ' ${ahead_count}  ${behind_count}'
behind = ' ${count} '
up_to_date = ' $count '
conflicted = ' $count '
untracked = ' $count '
format = '[$conflicted](red)[$stashed](251)[$untracked]($style)[$staged](green)[$modified](yellow)[$renamed](yellow)[$deleted](red)[$ahead]($style)[$behind]($style)[$diverged]($style)'

[package]
symbol = "  "
