---
- name: Install spotify package
  kewlfft.aur.aur:
    name: spotify
  when: ansible_distribution == "Archlinux"

- name: Deploy spotify.desktop
  ansible.builtin.file:
    src: "{{ role_path }}/files/spotify.desktop"
    dest: ~/.local/share/applications/spotify.desktop
    state: link
    force: true
