---
- name: Install google-chrome package
  kewlfft.aur.aur:
    name: google-chrome
  when: ansible_distribution == "Archlinux"

- name: Deploy google-chrome chrome-flags.conf
  ansible.builtin.file:
    src: "{{ role_path }}/files/chrome-flags.conf"
    dest: ~/.config/chrome-flags.conf
    state: link
    force: true
