---
- name: Install logid package
  community.general.pacman:
    name: logiops-git
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: Try disable logid systemd service
  become: true
  ansible.builtin.systemd:
    name: logid.service
    state: stopped
    enabled: false
  ignore_errors: true

- name: Deploy logid config
  become: true
  ansible.builtin.file:
    src: "{{ role_path }}/files/logid.cfg"
    dest: /etc/logid.cfg
    state: link
    force: true

- name: Run logid systemd service
  become: true
  ansible.builtin.systemd:
    name: logid.service
    state: started
    enabled: true
