---
- name: Install insomnia package
  kewlfft.aur.aur:
    name: insomnia-bin
  when: ansible_distribution == "Archlinux"

- name: Deploy insomnia.desktop
  ansible.builtin.file:
    src: "{{ role_path }}/files/insomnia.desktop"
    dest: ~/.local/share/applications/insomnia.desktop
    state: link
    force: true
