---
- name: Install insomnia package
  community.general.pacman:
    name: insomnia-bin
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: Deploy insomnia.desktop
  ansible.builtin.file:
    src: "{{ role_path }}/files/insomnia.desktop"
    dest: ~/.local/share/applications/insomnia.desktop
    state: link
    force: true
