---
- name: Install htop package
  become: true
  community.general.pacman:
    name: htop
  when: ansible_distribution == "Archlinux"

- name: Deploy rofi config
  ansible.builtin.file:
    src: "{{ role_path }}/files/htop"
    dest: ~/.config/htop
    state: link
    force: true
