---
- name: Install beekeeper package
  kewlfft.aur.aur:
    name: beekeeper-studio-bin
  when: ansible_distribution == "Archlinux"

- name: Deploy beekeeper-studio.desktop
  ansible.builtin.file:
    src: "{{ role_path }}/files/beekeeper-studio.desktop"
    dest: ~/.local/share/applications/beekeeper-studio.desktop
    state: link
    force: true
