---
- name: Install beekeeper package
  community.general.pacman:
    name: beekeeper-studio-bin
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: Deploy beekeeper-studio.desktop
  ansible.builtin.file:
    src: "{{ role_path }}/files/beekeeper-studio.desktop"
    dest: ~/.local/share/applications/beekeeper-studio.desktop
    state: link
    force: true
